CREATE TABLE IF NOT EXISTS `HBO`.`datos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dni` INT(11) NULL DEFAULT NULL,
  `dominio` VARCHAR(10) NULL DEFAULT NULL,
  `asegurado` VARCHAR(45) NULL DEFAULT NULL,
  `cobertura` VARCHAR(45) NULL DEFAULT NULL,
  `poliza` VARCHAR(45) NULL DEFAULT NULL,
  `vigencia_desde` VARCHAR(45) NULL DEFAULT NULL,
  `vigencia_hasta` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `anio` VARCHAR(45) NULL DEFAULT NULL,
  `chasis` VARCHAR(45) NULL DEFAULT NULL,
  `motor` VARCHAR(45) NULL DEFAULT NULL,
  `medioPago` VARCHAR(45) NULL DEFAULT NULL,
  `Productor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


CREATE TABLE IF NOT EXISTS `HBO`.`registracion` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_solicitud` DATETIME NULL DEFAULT NULL,
  `fecha_registracion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;



